# -*- coding: utf-8 -*-
"""LVADUSR186_Saswata_Pradhan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15YcqjJ5jKyGTPYvxz0jQyLgn0pp2jUuQ

1
"""

length= int(input('Enter the length in meter'))
width= int(input('Enter the width in meter'))

area=length*width

if  area<100:
  print('The area is small')
elif area<500:
  print('the area is medium')
else:
  print('The area is large')

"""2."""

weight=float(input("Enter your weight in Kg : "))
height=float(input("Enter your height in meter : "))
BMI=weight/(height)**2
print(f"BMI is {BMI}")

"""3"""

n=int(input('Enter the number of students : '))

names=[]
subjects=[]
grades=[]

students={}
for i in range(n):
  name= input(' Enter the Name')

  subject1= input('Enter sub 1')
  subjects.append(subject1)
  subject2= input('Enter sub 2')
  subjects.append(subject2)
  grade_sub1=int(input('Enter grade 1'))
  grades.append(grade_sub1)
  grade_sub2=int(input('Enter grade 2'))
  grades.append(grade_sub2)
  students[]

"""4"""

age=int(input('enter the age : '))


if age<12:
  print(' for children Watch movies with rating 5 ')
elif age < 18:
  print(' for adult Watch movies with rating 4.5')
elif age< 40:
  print(' for adult Watch movies rating 4 ')
else:
  print( ' for senior watch movies rating 3.5')

"""5"""

n=int(input(' Enter the number of id '))

even_ids=[]
for id in range (n+1):
  if id%2==0:
    even_ids.append(id)
    print('There is a new product launch')

even_ids

"""6"""

{}
password="Abc#"
while(True):
  p=input("Enter your password")
  if(p==password):
    print("Congrats You Entered Right Password")
    break
  else:
    print("Try Again")
    continue

"""7."""

no_of_customer=int(input())

score_=[]
def customer_feedback():


  for i in range(1,no_of_customer+1):

    score=float(input())
    score_.append(score)
    print('all')
score=customer_feedback()


avg_score=sum(score_)/no_of_customer
avg_score

"""8"""

def count_vowel(s):
  count=0
  for i in s:
    if (i=='a' or i=='e' or i=='i'or i=='o' or i=='u'):
      count+=1
  return count
s=input("Enter yor content")
print(f"Number of vowel present is {count_vowel(s)}")

"""9."""

from datetime import datetime
current_date_time=datetime.now()
print(f"The current date and time is {current_date_time}")

"""10"""

p=100
r=5/100
t=1
try:
  interest=p*r*t/100
  print(f'saving interest {interest}')
except :
    print("The system is not working")

"""11.

"""

try:

    result = "We Support" * "Enviroment"
    print(result)
except TypeError as e:
    print("TypeError occurred:", e)

"""12."""

try:
    result = 10 / 0

    print(result)
except ZeroDivisionError as e:
    print("ZeroDivisionError occurred:", e)

"""13"""

file_object = open("/content/-- Running total.txt", "w")

# Write content to the file
file_object.write("The time is 11:00!\n")
file_object.write("This is system is working fine.\n")

# Close the file
file_object.close()

"""14"""

file_object = open("/content/-- Running total.txt", "r")

content = file_object.read()
print(content)

line = file_object.readline()
print(line)

lines = file_object.readlines()
for line in lines:
    print(line)

"""15"""

file_object = open("/content/-- Running total.txt", "a")

file_object.write("This Company is working fine with stocks 52 weeks high")

file_object.close()

